### ISSUE TITLE
Cannot create a second table

### ISSUE THREAD

**Issue by dkarchmer** [shimizukawa/django-redshift-backend#21]
I have been using redshift with this package successfully with one model, but as I tried to create a second model on the redshift database, the migration step fails with

`django.db.utils.NotSupportedError: ALTER/CREATE TABLE column CHECK constraint is not supported`

The model is almost identical to the other one I have been using. I don't understand what `column CHECK constraint` is but everything looks ok. If I move this table to my second database, which is a vanilla Postgress, everything works fine.

Any ideas? Can I really only store one table per rredshift?

Complete stack:

```
 Running migrations:
  Applying streamevent.0001_initial...Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 63, in execute
  return self.cursor.execute(sql)
  File "/opt/python/run/venv/local/lib64/python3.4/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 169, in execute
  return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/opt/python/run/venv/local/lib64/python3.4/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 180, in _trace_sql
  return method(sql)
  psycopg2.NotSupportedError: ALTER/CREATE TABLE column CHECK constraint is not supported
  
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
  File "/opt/python/run/venv/bin/django-admin.py", line 5, in <module>
  management.execute_from_command_line()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
  utility.execute()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 355, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
  self.execute(*args, **cmd_options)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
  output = self.handle(*args, **options)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 204, in handle
  fake_initial=fake_initial,
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 115, in migrate
  state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
  state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
  state = migration.apply(state, schema_editor)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/migrations/migration.py", line 129, in apply
  operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
  schema_editor.create_model(model)
  File "/opt/python/ondeck/app/apps/redshift_backend/base.py", line 184, in create_model
  self.execute(sql, params or None)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 119, in execute
  cursor.execute(sql, params)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
  return self.cursor.execute(sql, params)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
  six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
  raise value.with_traceback(tb)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 63, in execute
  return self.cursor.execute(sql)
  File "/opt/python/run/venv/local/lib64/python3.4/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 169, in execute
  return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/opt/python/run/venv/local/lib64/python3.4/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 180, in _trace_sql
  return method(sql)
  django.db.utils.NotSupportedError: ALTER/CREATE TABLE column CHECK constraint is not supported
  
   (ElasticBeanstalk::ExternalInvocationError)

```

**Comment by shimizukawa** [comment]
I think it is same as #15.

**Comment by shimizukawa** [comment]
Now #15 is fixed.
