### ISSUE TITLE
AttributeError: 'AutoField' object has no attribute 'rel'

### ISSUE THREAD

**Issue by wally-yu** [shimizukawa/django-redshift-backend#47]
Subject: Encounter issue when migrate

### Problem
- Dear team,
This package helps a lot, thanks for develop such a tool.
But I followed the doc, while I want to migrate, below issue happens:

```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, redshift, sessions
Running migrations:
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/py3/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/venv/py3/lib/python3.4/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/py3/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/py3/lib/python3.4/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/venv/py3/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/venv/py3/lib/python3.4/site-packages/django/db/migrations/executor.py", line 91, in migrate
    self.recorder.ensure_schema()
  File "/venv/py3/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 55, in ensure_schema
    editor.create_model(self.Migration)
  File "/venv/py3/lib/python3.4/site-packages/django_redshift_backend/base.py", line 168, in create_model
    if field.rel and field.db_constraint:
AttributeError: 'AutoField' object has no attribute 'rel'
```

### Environment info
- OS: Linux version 4.14.62-65.117.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2)
- Python version: Python 3.4.3
- Django version: Tried Django 1.11, 2.05 and 2.08, all the same

Here is my setting:
```
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django_redshift_backend',
        'NAME': 'name',
        'USER': 'root',
        'PASSWORD': 'psw',
        'HOST': 'host',
        'PORT': '5439',
    }
}
```

Model file:
```
from django.db import models

# Create your models here.

class test_redshift_django(models.Model):
    _database = 'redshift_db'
    name = models.CharField(max_length=10)
```

Migration file:
```
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_redshift_django',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
```

Could you please help take a look what might goes wrong?

**Comment by okgarces** [comment]
I had the 0.7 version installed.
I upgrade it to 0.9 and check the code the constraint was different.

**Comment by okgarces** [comment]
Right now I am using the latest version for Django v2.0.5. The latest version is 0.9

**Comment by wally-yu** [comment]
hi @okgarces do you have a chance to reproduce this issue from your side?

**Comment by shimizukawa** [comment]
@wally-yu  I think you are using django-redshfit-backend 0.8 or 0.8.1, and it doesn't support Django-2.x. Please use `django-redshfit-backend-0.9` that supports Django-2.0.

Feel free to reopen if you still have this issue.
