### ISSUE TITLE
Django1.7 error on DatabaseWrapper ( no attribute "data_types" )

### ISSUE THREAD

**Issue by inakidelamadrid** [shimizukawa/django-redshift-backend#7]
This is my stack trace,
```
>>> TXCache.objects.using('redshift').count()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ignaciodelamadrid/Development/venturefund.io/lib/python2.7/site-packages/django/db/models/query.py", line 338, in count
    return self.query.get_count(using=self.db)
  File "/Users/ignaciodelamadrid/Development/venturefund.io/lib/python2.7/site-packages/django/db/models/sql/query.py", line 436, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "/Users/ignaciodelamadrid/Development/venturefund.io/lib/python2.7/site-packages/django/db/models/sql/query.py", line 402, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "/Users/ignaciodelamadrid/Development/venturefund.io/lib/python2.7/site-packages/django/db/models/sql/query.py", line 224, in get_compiler
    connection = connections[using]
  File "/Users/ignaciodelamadrid/Development/venturefund.io/lib/python2.7/site-packages/django/db/utils.py", line 242, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/ignaciodelamadrid/Development/venturefund.io/lib/python2.7/site-packages/django/db/utils.py", line 108, in load_backend
    return import_module('%s.base' % backend_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/ignaciodelamadrid/Development/venturefund.io/venturefund/db/backends/django-redshift/base.py", line 402, in <module>
    class DatabaseWrapper(BasePGDatabaseWrapper):
  File "/Users/ignaciodelamadrid/Development/venturefund.io/venturefund/db/backends/django-redshift/base.py", line 406, in DatabaseWrapper
    data_types = deepcopy(BasePGDatabaseWrapper.data_types)
AttributeError: type object 'DatabaseWrapper' has no attribute 'data_types'
```

I saw Django's repo and it seems that the 1.7 version doesn't declare the data_types dictionary in the DatabaseWrapper class in the django.db.backends.postgresql_psycopg2 module. Any hint on this? Are you guys going to support 1.7? upgrading is kind of difficult for me.

**Comment by shimizukawa** [comment]
Thanks for your reporting. I'll take a look.

**Comment by shimizukawa** [comment]
Fixed.
